/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vehservicemgmt;

import java.sql.SQLException;
import java.util.Vector;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author bhave
 */
public class PartsDialog extends javax.swing.JDialog {
    
    private int partId = -1;
    
    /**
     * Creates new form PartsDialog
     */
    public PartsDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        partID.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        partID = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        partName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        brand = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        mrp = new javax.swing.JTextField();
        partAdd = new javax.swing.JButton();
        partCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jLabel1.setText("Part ID");

        partID.setText("Automatic");

        jLabel2.setText("Part Name");

        partName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                partNameKeyTyped(evt);
            }
        });

        jLabel3.setText("Brand");

        brand.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                brandKeyTyped(evt);
            }
        });

        jLabel4.setText("MRP");

        mrp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                mrpKeyTyped(evt);
            }
        });

        partAdd.setText("Add");
        partAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                partAddActionPerformed(evt);
            }
        });

        partCancel.setText("Cancel");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(partID)
                            .addComponent(partName, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE)
                            .addComponent(brand)
                            .addComponent(mrp)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(partAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(partCancel)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(partID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(partName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(brand, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(mrp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(partAdd)
                    .addComponent(partCancel))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public void InfoDialog(String message){
        JFrame f = new JFrame();
        JOptionPane.showMessageDialog(f, message);
    }
    
    public void updateDetails(int pid) throws SQLException{
        partId = pid;
        Vector partDetails = dbconn.partSearch(pid);
        partID.setText(partDetails.get(0).toString());
        partName.setText((String)partDetails.get(1));
        brand.setText((String)partDetails.get(2));
        mrp.setText(partDetails.get(3).toString());
    }
    
    private void partAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_partAddActionPerformed
        try {
            Vector values = new Vector();
            if (!partName.getText().isEmpty() && !brand.getText().isEmpty() &&
                    !mrp.getText().isEmpty()) {
                values.add(partName.getText());
                values.add(brand.getText());
                values.add(mrp.getText());
                if (!((String)mrp.getText()).equals("") && ((String)mrp.getText()).matches("^[1-9]\\d{1,5}$")){
                    if(partId == -1){
                        dbconn.partInsert(values);
                        this.dispose();
                    }
                    else{
                        values.add(partId);
                        dbconn.partUpdate(values);
                        this.dispose();
                    }
                }else{
                    InfoDialog("Invalid MRP.");
                }
            }
        } catch (Exception e) {
            System.out.println("vehAddActionPerformed block:"+e);
            InfoDialog("Fill all information.");
        }
    }//GEN-LAST:event_partAddActionPerformed

    private void mrpKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_mrpKeyTyped
        // TODO add your handling code here:
        MainFrame.onlyNumber(evt);
    }//GEN-LAST:event_mrpKeyTyped

    private void partNameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_partNameKeyTyped
        // TODO add your handling code here:
        MainFrame.letterNumSpace(evt);
    }//GEN-LAST:event_partNameKeyTyped

    private void brandKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_brandKeyTyped
        // TODO add your handling code here:
        MainFrame.letterNumSpace(evt);
    }//GEN-LAST:event_brandKeyTyped

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PartsDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PartsDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PartsDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PartsDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                PartsDialog dialog = new PartsDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField brand;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField mrp;
    public javax.swing.JButton partAdd;
    private javax.swing.JButton partCancel;
    private javax.swing.JTextField partID;
    private javax.swing.JTextField partName;
    // End of variables declaration//GEN-END:variables
}
