/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vehservicemgmt;

import com.sun.glass.events.KeyEvent;
import java.awt.Toolkit;
import java.awt.event.ItemEvent;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Vector;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import org.jdesktop.swingx.autocomplete.AutoCompleteDecorator;
import org.jdesktop.swingx.combobox.ListComboBoxModel;

/**
 *
 * @author bhave
 */
public class ServiceDialog extends javax.swing.JDialog {

    /**
     * Creates new form ServiceDialog
     */
    
    private Vector custDetails = null;
    private Vector vehDetails = null;
    private Vector empDetails = null;
    private int serviceID = -1;
    
    public ServiceDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        try {
            custDetails =  dbconn.custDetails();
            empDetails = dbconn.empDetails();
            ArrayList<String> names = new ArrayList<String>();
            for (int i = 0; i < custDetails.size(); i++){
                Vector inner = (Vector)custDetails.elementAt(i);
                names.add((String)inner.get(1));
            }
            Collections.sort(names);
            custName.setEditable(true);
            custName.setModel(new ListComboBoxModel<String>(names));
            custName.setSelectedIndex(-1);
            AutoCompleteDecorator.decorate(custName);
            ArrayList<String> sa = new ArrayList<String>();
            for (int i = 0; i < empDetails.size(); i++){
                Vector inner = (Vector)empDetails.elementAt(i);
                sa.add((String)inner.get(1));
            }
            serviceAdvisor.setModel(new ListComboBoxModel<String>(sa));
            serviceAdvisor.setSelectedIndex(-1);
            AutoCompleteDecorator.decorate(serviceAdvisor);
        } catch (SQLException ex) {
            Logger.getLogger(ServiceDialog.class.getName()).log(Level.SEVERE, null, ex);
        }
        regNo.removeAllItems();
        regNo.setSelectedIndex(-1);
        DateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        Date date = new Date();
        serviceDate.setDate(date);
        address.setEditable(false);
        contactNo.setEditable(false);
        vehType.setEditable(false);
        vehModel.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CustDetail = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        address = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        contactNo = new javax.swing.JTextField();
        custName = new javax.swing.JComboBox<>();
        VehDetail = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        vehType = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        vehModel = new javax.swing.JTextField();
        regNo = new javax.swing.JComboBox<>();
        ServiceDetail = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        serviceDate = new com.toedter.calendar.JDateChooser();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jobDesc = new javax.swing.JTextArea();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        distance = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        damages = new javax.swing.JTextArea();
        jPanel4 = new javax.swing.JPanel();
        serviceAdd = new javax.swing.JButton();
        serviceCancel = new javax.swing.JButton();
        serviceAdvisor = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Customer Name");

        jLabel2.setText("Address");

        jLabel3.setText("Contact No.");

        custName.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        custName.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                custNameItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout CustDetailLayout = new javax.swing.GroupLayout(CustDetail);
        CustDetail.setLayout(CustDetailLayout);
        CustDetailLayout.setHorizontalGroup(
            CustDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CustDetailLayout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(contactNo, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE))
            .addGroup(CustDetailLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(custName, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(CustDetailLayout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(address))
        );
        CustDetailLayout.setVerticalGroup(
            CustDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CustDetailLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(CustDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(custName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(CustDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(address, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(CustDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(contactNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel4.setText("Registration No.");

        jLabel5.setText("Type");

        jLabel6.setText("Model");

        regNo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        regNo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                regNoItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout VehDetailLayout = new javax.swing.GroupLayout(VehDetail);
        VehDetail.setLayout(VehDetailLayout);
        VehDetailLayout.setHorizontalGroup(
            VehDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(VehDetailLayout.createSequentialGroup()
                .addGroup(VehDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(VehDetailLayout.createSequentialGroup()
                        .addGroup(VehDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(VehDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(vehType, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE)
                            .addComponent(regNo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(VehDetailLayout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(vehModel, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        VehDetailLayout.setVerticalGroup(
            VehDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(VehDetailLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(VehDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(regNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(VehDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(vehType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(VehDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(vehModel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel7.setText("Service Date");

        serviceDate.setDateFormatString("YYYY-MM-dd");

        jLabel8.setText("Job Description");

        jobDesc.setColumns(20);
        jobDesc.setRows(5);
        jScrollPane1.setViewportView(jobDesc);

        jLabel9.setText("Service Advisor");

        jLabel10.setText("Distance");

        distance.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                distanceKeyTyped(evt);
            }
        });

        jLabel11.setText("Damages");

        damages.setColumns(20);
        damages.setRows(5);
        jScrollPane2.setViewportView(damages);

        serviceAdd.setText("Add");
        serviceAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                serviceAddActionPerformed(evt);
            }
        });

        serviceCancel.setText("Cancel");
        serviceCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                serviceCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(serviceAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(serviceCancel, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(serviceAdd)
                    .addComponent(serviceCancel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        serviceAdvisor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout ServiceDetailLayout = new javax.swing.GroupLayout(ServiceDetail);
        ServiceDetail.setLayout(ServiceDetailLayout);
        ServiceDetailLayout.setHorizontalGroup(
            ServiceDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ServiceDetailLayout.createSequentialGroup()
                .addGroup(ServiceDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(ServiceDetailLayout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(serviceAdvisor, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(ServiceDetailLayout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(serviceDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(ServiceDetailLayout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ServiceDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ServiceDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2)
                    .addComponent(distance))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ServiceDetailLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(176, 176, 176))
        );
        ServiceDetailLayout.setVerticalGroup(
            ServiceDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ServiceDetailLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ServiceDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(serviceDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addGroup(ServiceDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel10)
                        .addComponent(distance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(ServiceDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ServiceDetailLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(ServiceDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(ServiceDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(serviceAdvisor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(58, 58, 58))
                    .addGroup(ServiceDetailLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ServiceDetail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(CustDetail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(VehDetail, javax.swing.GroupLayout.PREFERRED_SIZE, 263, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(VehDetail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CustDetail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ServiceDetail, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public static void InfoDialog(String message){
        JFrame f = new JFrame();
        JOptionPane.showMessageDialog(f, message);
    }
          
    public void updateDetails(int ID) throws SQLException, ParseException{
        serviceID = ID;
        Vector servicedetail = dbconn.serviceDetailByID(ID);
        System.out.println(servicedetail);
        custName.setSelectedItem(servicedetail.get(6));
        regNo.setSelectedItem(servicedetail.get(5));
        serviceAdvisor.setSelectedItem(servicedetail.get(7));
        serviceDate.setDate(new SimpleDateFormat("yyyy-MM-DD").parse(servicedetail.get(2).toString()));
        jobDesc.setText(servicedetail.get(1).toString());
        distance.setText(servicedetail.get(3).toString());
        damages.setText(servicedetail.get(4).toString());
    }
    
    private void serviceCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_serviceCancelActionPerformed
        this.dispose();
    }//GEN-LAST:event_serviceCancelActionPerformed

    private void custNameItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_custNameItemStateChanged
        if (evt.getStateChange() == ItemEvent.SELECTED){
            Vector cust = null;
            int i;
            if(custName.getSelectedIndex() != -1){
                for (i = 0; i < custDetails.size(); i++){
                    Vector inner = (Vector)custDetails.elementAt(i);
                    if(inner.contains(custName.getSelectedItem())){
                        cust = (Vector)custDetails.elementAt(i);
                        break;
                    }
                }
                address.setText((String)cust.elementAt(2));
                contactNo.setText((String)cust.elementAt(3));
                
                try {
                    vehDetails = (Vector)dbconn.vehDetailsByCustomer((int)cust.elementAt(0));
                } catch (SQLException ex) {
                    Logger.getLogger(ServiceDialog.class.getName()).log(Level.SEVERE, null, ex);
                }
                ArrayList<String> items = new ArrayList<String>();
                for ( i = 0; i < vehDetails.size(); i++){
                    Vector inner = (Vector)vehDetails.elementAt(i);
                    items.add((String)inner.get(1));
                }
                regNo.setEditable(false);
                regNo.setModel(new ListComboBoxModel<String>(items));
                regNo.setSelectedIndex(-1);
            }
        }
    }//GEN-LAST:event_custNameItemStateChanged

    private void regNoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_regNoItemStateChanged
        if (evt.getStateChange() == ItemEvent.SELECTED){
            int index = regNo.getSelectedIndex();
            Vector record = (Vector)vehDetails.elementAt(index);
            vehModel.setText((String)record.elementAt(3));
            vehType.setText((String)record.elementAt(4));
        }
    }//GEN-LAST:event_regNoItemStateChanged

    private void serviceAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_serviceAddActionPerformed
        try{
            Vector values = new Vector();
            if (!jobDesc.getText().isEmpty() && !distance.getText().isEmpty() && 
                    !damages.getText().isEmpty()) {
                System.out.println("if block");
                String date=((JTextField)serviceDate.getDateEditor().getUiComponent()).getText();
                String jobdesc = jobDesc.getText();
                String dist = this.distance.getText();
                String dmgs = damages.getText();
                Vector record = (Vector)vehDetails.elementAt(regNo.getSelectedIndex());
                Long vehid =  (Long)record.elementAt(0);
                record =  (Vector)empDetails.elementAt(serviceAdvisor.getSelectedIndex());
                int empid = (Integer)record.elementAt(0);
                values.add(date);
                values.add(jobdesc);
                values.add(dist);
                values.add(dmgs);
                values.add(vehid);
                values.add(empid);
            }
            if(custName.getSelectedItem()!=null && regNo.getSelectedItem()!=null
                    && serviceAdvisor.getSelectedItem()!=null){
                if(serviceID == -1){
                    dbconn.serviceInsert(values);
                    this.dispose();
                }
                else{
                    values.add(serviceID);
                    dbconn.serviceUpdate(values);
                    this.dispose();
                }
            }
        }
        catch(Exception e){
            System.out.println("serviceAddActionPerformed block:"+e);
            InfoDialog("Fill all information.");
        }
    }//GEN-LAST:event_serviceAddActionPerformed

    private void distanceKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_distanceKeyTyped
        // TODO add your handling code here:
        MainFrame.onlyNumber(evt);
    }//GEN-LAST:event_distanceKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ServiceDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ServiceDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ServiceDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ServiceDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ServiceDialog dialog = new ServiceDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel CustDetail;
    private javax.swing.JPanel ServiceDetail;
    private javax.swing.JPanel VehDetail;
    private javax.swing.JTextField address;
    private javax.swing.JTextField contactNo;
    private javax.swing.JComboBox<String> custName;
    private javax.swing.JTextArea damages;
    private javax.swing.JTextField distance;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jobDesc;
    private javax.swing.JComboBox<String> regNo;
    public javax.swing.JButton serviceAdd;
    private javax.swing.JComboBox<String> serviceAdvisor;
    private javax.swing.JButton serviceCancel;
    private com.toedter.calendar.JDateChooser serviceDate;
    private javax.swing.JTextField vehModel;
    private javax.swing.JTextField vehType;
    // End of variables declaration//GEN-END:variables
}
