/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vehservicemgmt;

import java.awt.event.ItemEvent;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import org.jdesktop.swingx.autocomplete.AutoCompleteDecorator;
import org.jdesktop.swingx.combobox.ListComboBoxModel;

/**
 *
 * @author bhave
 */
public class VehicleDialog extends javax.swing.JDialog {
    
    private Vector custDetails = null;
    private Vector vehDetails = null;
    private long vID = -1;

    /**
     * Creates new form VehicleDialog
     */
    
    
    public VehicleDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        try {
            custDetails =  dbconn.custDetails();
            ArrayList<String> names = new ArrayList<String>();
            for (int i = 0; i < custDetails.size(); i++){
                Vector inner = (Vector)custDetails.elementAt(i);
                names.add((String)inner.get(1));
            }
            custName.setEditable(true);
            custName.setModel(new ListComboBoxModel<String>(names));
            custName.setSelectedIndex(-1);
            AutoCompleteDecorator.decorate(custName);
            vehID.setEditable(false);
            address.setEditable(false);
            contactNo.setEditable(false);
            manual.setSelected(true);
        } catch (SQLException ex) {
            Logger.getLogger(ServiceDialog.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        transmissionGroup = new javax.swing.ButtonGroup();
        CustDetail = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        address = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        contactNo = new javax.swing.JTextField();
        custName = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        vehID = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        regNo = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        company = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        model = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        type = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        manual = new javax.swing.JRadioButton();
        automatic = new javax.swing.JRadioButton();
        jPanel2 = new javax.swing.JPanel();
        vehAdd = new javax.swing.JButton();
        vehCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Customer Name");

        jLabel2.setText("Address");

        jLabel3.setText("Contact No.");

        custName.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        custName.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                custNameItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout CustDetailLayout = new javax.swing.GroupLayout(CustDetail);
        CustDetail.setLayout(CustDetailLayout);
        CustDetailLayout.setHorizontalGroup(
            CustDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CustDetailLayout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(contactNo))
            .addGroup(CustDetailLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(custName, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(CustDetailLayout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(address))
        );
        CustDetailLayout.setVerticalGroup(
            CustDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CustDetailLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(CustDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(custName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(CustDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(address, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(CustDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(contactNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel4.setText("Vehicle ID");

        vehID.setText("Automatic");

        jLabel5.setText("Registration No");

        regNo.setToolTipText("LL11LL1111");
        regNo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                regNoKeyTyped(evt);
            }
        });

        jLabel6.setText("Company");

        company.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                companyKeyTyped(evt);
            }
        });

        jLabel7.setText("Model");

        model.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                modelKeyTyped(evt);
            }
        });

        jLabel8.setText("Type");

        type.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                typeKeyTyped(evt);
            }
        });

        jLabel9.setText("Transmission");

        transmissionGroup.add(manual);
        manual.setText("Manual");

        transmissionGroup.add(automatic);
        automatic.setText("Automatic");

        vehAdd.setText("Add");
        vehAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vehAddActionPerformed(evt);
            }
        });

        vehCancel.setText("Cancel");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addComponent(vehAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(vehCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(106, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(vehAdd)
                    .addComponent(vehCancel))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(vehID)
                    .addComponent(regNo)
                    .addComponent(company)
                    .addComponent(model)
                    .addComponent(type)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(manual)
                        .addGap(18, 18, 18)
                        .addComponent(automatic)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(vehID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(regNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(company, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(model, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(type, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(manual)
                    .addComponent(automatic))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(CustDetail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(CustDetail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public void updateDetails(Long ID) throws SQLException{
        vID = ID;
        Vector cust = null;
        int custId=-1;
        Vector vehDetail = dbconn.vehSearch(ID);
        custId = (int)vehDetail.get(6);
        for (int i = 0; i < custDetails.size(); i++){
            Vector inner = (Vector)custDetails.elementAt(i);
            if(inner.contains(custId)){
                cust = (Vector)custDetails.elementAt(i);
                break;
            }
        }
        vehID.setText(vehDetail.get(0).toString());
        custName.setSelectedItem(cust.get(1));
        regNo.setText((String)vehDetail.get(1));
        company.setText((String)vehDetail.get(2));
        model.setText((String)vehDetail.get(3));
        type.setText((String)vehDetail.get(4));
        System.out.println((String)vehDetail.get(5));
        
        if (((String)vehDetail.get(5)).equals("automatic")) {
            automatic.setSelected(true);
        }
        else{
            manual.setSelected(true);
        }
    }
    
    private void custNameItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_custNameItemStateChanged
        if (evt.getStateChange() == ItemEvent.SELECTED){
            int ind = custName.getSelectedIndex();
            if(ind != -1){
                Vector record = (Vector)custDetails.elementAt(ind);
                address.setText((String)record.elementAt(2));
                contactNo.setText((String)record.elementAt(3));
            }
        }
    }//GEN-LAST:event_custNameItemStateChanged

    private void vehAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vehAddActionPerformed
        // TODO add your handling code here:
        try {
            Vector values = new Vector();
            if (!regNo.getText().isEmpty() && !company.getText().isEmpty() &&
                    !model.getText().isEmpty()) {
                values.add(regNo.getText());
                values.add(company.getText());
                values.add(model.getText());
                values.add(type.getText());
                if(manual.isSelected())
                    values.add("Manual");
                if (automatic.isSelected()) 
                    values.add("Automatic");
                Vector record = (Vector)custDetails.elementAt(custName.getSelectedIndex());
                values.add((Integer)record.elementAt(0));
            }
            if(!((String)regNo.getText()).equals("") && ((String)regNo.getText()).matches("^[A-Z]{2}[0-9]{2}[A-Z]{1,2}[0-9]{4}$")){
                if (!((String)company.getText()).equals("") && ((String)company.getText()).matches("^[#.0-9a-zA-Z\\s,-]+$")) {
                    if(custName.getSelectedItem()!=null){
                        if(vID == -1){
                            dbconn.vehInsert(values);
                            this.dispose();
                        }
                        else{
                            values.add(vID);
                            dbconn.vehUpdate(values);
                            this.dispose();
                        }
                    }
                }
                else{
                    InfoDialog("Invalid Company name.");
                }
            }
            else{
                InfoDialog("Invalid vehicle number.");
            }
        } catch (Exception e) {
            System.out.println("vehAddActionPerformed block:"+e);
            InfoDialog("Fill all information.");
        }
        
        
    }//GEN-LAST:event_vehAddActionPerformed

    private void companyKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_companyKeyTyped
        // TODO add your handling code here:
        MainFrame.letterNumSpace(evt);
    }//GEN-LAST:event_companyKeyTyped

    private void regNoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_regNoKeyTyped
        // TODO add your handling code here:
        MainFrame.letterNumbers(evt);
    }//GEN-LAST:event_regNoKeyTyped

    private void modelKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_modelKeyTyped
        // TODO add your handling code here:
        MainFrame.letterNumSpace(evt);
    }//GEN-LAST:event_modelKeyTyped

    private void typeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_typeKeyTyped
        // TODO add your handling code here:
        MainFrame.letterSpace(evt);
    }//GEN-LAST:event_typeKeyTyped

    public void InfoDialog(String message){
        JFrame f = new JFrame();
        JOptionPane.showMessageDialog(f, message);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VehicleDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VehicleDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VehicleDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VehicleDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                VehicleDialog dialog = new VehicleDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel CustDetail;
    private javax.swing.JTextField address;
    private javax.swing.JRadioButton automatic;
    private javax.swing.JTextField company;
    private javax.swing.JTextField contactNo;
    private javax.swing.JComboBox<String> custName;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton manual;
    private javax.swing.JTextField model;
    private javax.swing.JTextField regNo;
    private javax.swing.ButtonGroup transmissionGroup;
    private javax.swing.JTextField type;
    public javax.swing.JButton vehAdd;
    private javax.swing.JButton vehCancel;
    private javax.swing.JTextField vehID;
    // End of variables declaration//GEN-END:variables
}
